import React from "react";
import { Modal, Button, Alert } from "antd";
import { useUserMap, getFirstNameFromUserId } from "../../hooks/useUserMap";

// Helper to format ISO date-time to Indian Standard Time (IST)
const formatDateTimeToIST = (dateVal) => {
  if (!dateVal) return '-';
  try {
    let dateStr = String(dateVal);
    // If it doesn't end with Z and doesn't contain a timezone offset, and is in ISO-like format, append 'Z'
    if (
      !dateStr.endsWith('Z') &&
      !dateStr.includes('+') &&
      !dateStr.match(/-\d{2}:\d{2}$/)
    ) {
      if (dateStr.includes(' ') && !dateStr.includes('T')) {
        dateStr = dateStr.replace(' ', 'T');
      }
      dateStr = `${dateStr}Z`;
    }
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return '-';
    
    return d.toLocaleString('en-IN', {
      timeZone: 'Asia/Kolkata',
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: true,
    });
  } catch (e) {
    return '-';
  }
};

const ExistingReportModal = ({ visible, report, onDownload, onGenerate, onCancel }) => {
  const { userMap } = useUserMap();

  let generatedByUserId = report?.generatedByUserId || report?.GeneratedByUserId;
  let fallbackName = report?.generatedBy || report?.GeneratedBy || "-";
  let generatedByName = (generatedByUserId ? getFirstNameFromUserId(generatedByUserId, userMap) : null) || fallbackName;

  return (
    <Modal
      title="Report Already Exists"
      open={visible}
      onCancel={onCancel}
      width={500}
      footer={[
        <Button key="cancel" onClick={onCancel}>
          Cancel
        </Button>,
        <Button key="download" type="default" onClick={onDownload}>
          Download Existing
        </Button>,
        <Button key="generate" type="primary" onClick={onGenerate}>
          Generate New
        </Button>,
      ]}
    >
      {report && (
        <div>
          <Alert
            message="A report already exists for this template and envelope lot combination"
            description={
              <div style={{ marginTop: 8 }}>
                <p><strong>Template:</strong> {report.templateName}</p>
                <p><strong>Envelope Lots:</strong> {report.envLotNumbers ? (Array.isArray(report.envLotNumbers) ? report.envLotNumbers.join(', ') : report.envLotNumbers) : '-'}</p>
                <p><strong>Generated:</strong> {formatDateTimeToIST(report.generatedAt || report.GeneratedAt)}</p>
                <p><strong>Generated By:</strong> {generatedByName}</p>
              </div>
            }
            type="warning"
            showIcon
            style={{ marginBottom: 16 }}
          />
          <p>You can download the existing report or generate a new one to replace it.</p>
        </div>
      )}
    </Modal>
  );
};

export default ExistingReportModal;
