import React from "react";
import { Modal, Button, Alert } from "antd";

const ExistingReportModal = ({ visible, report, onDownload, onGenerate, onCancel }) => {
  return (
    <Modal
      title="Report Already Exists"
      open={visible}
      onCancel={onCancel}
      width={500}
      footer={[
        <Button key="cancel" onClick={onCancel}>
          Cancel
        </Button>,
        <Button key="download" type="default" onClick={onDownload}>
          Download Existing
        </Button>,
        <Button key="generate" type="primary" onClick={onGenerate}>
          Generate New
        </Button>,
      ]}
    >
      {report && (
        <div>
          <Alert
            message="A report already exists for this template and envelope lot combination"
            description={
              <div style={{ marginTop: 8 }}>
                <p><strong>Template:</strong> {report.templateName}</p>
                <p><strong>Envelope Lots:</strong> {report.envLotNumbers.join(', ')}</p>
                <p><strong>Generated:</strong> {new Date(report.generatedAt).toLocaleString()}</p>
                <p><strong>Generated By:</strong> {report.generatedBy}</p>
              </div>
            }
            type="warning"
            showIcon
            style={{ marginBottom: 16 }}
          />
          <p>You can download the existing report or generate a new one to replace it.</p>
        </div>
      )}
    </Modal>
  );
};

export default ExistingReportModal;
